// <auto-generated />
using System;
using BirdingJournal.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BirdingJournal.Migrations
{
    [DbContext(typeof(BirdingJournalDbContext))]
    [Migration("20230424234603_Second")]
    partial class Second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BirdingJournal.Models.Bird", b =>
                {
                    b.Property<long>("BirdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BirdID"));

                    b.Property<string>("BirdDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirdHabitat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirdScientificName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirdyCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BirdID");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("BirdingJournal.Models.BirdSighting", b =>
                {
                    b.Property<long?>("BirdSightingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("BirdSightingID"));

                    b.Property<string>("BirdCommonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("BirdID")
                        .HasColumnType("bigint");

                    b.Property<string>("IsFemale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsJuvenile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SpottedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("User_ID")
                        .HasColumnType("bigint");

                    b.HasKey("BirdSightingID");

                    b.ToTable("BirdSightings");
                });

            modelBuilder.Entity("BirdingJournal.Models.User_", b =>
                {
                    b.Property<int>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
